In [27]:
import numpy as np
import matplotlib.pyplot as plt


In [82]:
# Question 1
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([9,8,11,12,11,13,14,15,16,17])

print(x)
print(y)


[ 1  2  3  4  5  6  7  8  9 10]
[ 9  8 11 12 11 13 14 15 16 17]


In [83]:
# # x1=np.array([1,2,3])
# y1=np.array([1,2,3])
# sum(y1)**2
# # sum(x1*y1)

In [84]:
sum(x*y)


771

In [85]:
# # Question 2
# X = np.array([158,166,163,165,167,170,167,172,177,181])
# Y = np.array([163,158,167,170,160,180,170,175,172,175])

# print(X)
# print(Y)


In [86]:
# y= a1 + a2*x + b

In [87]:
# Regression coefficient of y on x

a1 = (n*sum(x*y)-sum(x)*sum(y)) / (n*sum(x*x)-sum(x)**2) #regression y on x
a1


0.9454545454545454

In [91]:
a2 = (n*sum(x*y)-sum(x)*sum(y)) / (n*sum(y*y)-sum(y)**2) #regression x on y
a2

0.9948979591836731

In [92]:
y = a1 + a2*x

In [93]:
y

array([ 1.98979592,  2.98469388,  3.97959184,  4.9744898 ,  5.96938776,
        6.96428571,  7.95918367,  8.95408163,  9.94897959, 10.94387755])